# Generated by Django 3.0.7 on 2020-06-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
